const titles = [
  "Support and I'll do more ❤️ ", 
  "I am pleased when your arrow rises in my post ❤️ ", 
  "Thank you for watching 😍 🔥 🍓 ", 
  "Still 🍓 😍 ", 
  "don't forget to support through the voice 😍🔥", 
  "Thank you for the voice ⬆️ ", 
  "Photo and your voice ⬆️ ", 
  "⬆️😍⬆️😍⬆️😍",
  "I bet your cock would make me cum so much better",
  "Showing you my slutty object",
  "Would your allow me to bounce on your cock if I'll be your personal slut?",
  "All you gotta do is move thong to the side and it's yours ☺️",
  "I know.... I'm slutty",
  "How deep could you fit inside my tight pussy 🥰",
  "i won't stop grinding until i drained your balls",
  "I know.. I'm slutty.",
  "would you date a serial flasher? 😝",
  "Showing you the slut that hides under these clothes😛",
  "Can I convince any older guy to give me a juicy load?🤤",
  "Am i the slut you'd fuck three times in a row?😲",
  "do they look good for my height even though they are pierced?",
  "does the fact this milf sleeps with all her friends married husbands make her a slut",
  "Can I convince you to fuck my wet pussy",
  "I found a place for us :)",
  "Can we swap nudes?",
  "Come into bed and let's fuck",
  "I can give a ride with me if you insert your cock in my tight pussy",
  "Can I sit on you instead? 😽",
  "Just some fat pussy and slutty boobs",
  "Silk skin",
  "Anyone wanna be coworkers?",
  "Roses are red, violets are blue, I'm bad at poems so here's my tits",
  "wanna slide right in me ?",
  "I almost never post full body pics on here so I'm really nervous- Anyone think I should post more though?",
  "Guess how deep could you fit in? Take my tightness into consideration",
  "Can I be your favorite fuckbunny?",
  "My naked body for your good mood",
  "Ready to fulfil your desires",
  "Would you still use me as your slut despite my tiny tits?",
  "Thought some of you may appreciate this",
  "Cute girls can be very dirty",
  "I promise I'm not a slut 🙈",
  "This ride ends only after I drained your balls",
  "How deep could you fit inside my tight pussy 🥰",
  "If you didn't know, petite blondes are your weakness 😌",
  "Put it in with my lingere on or should it be off?",
  "I've been told I'm the perfect age to be your slut",
  "Would you get filthy with us?",
  "not perfect but all natural",
  "This ride ends only after I drained your balls",
  "Replying on your naughty text like this",
  "my biggest sin is letting 100% of men cum inside",
  "Seductive entrancement",
  "Slutty bunny girl",
  "Fine I'll take it off"
]

export default () => titles[parseInt(Math.random() * titles.length)]